version: '3.9'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    ports:
      - "5044:5044"
    networks:
      - elk

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - elk

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak?characterEncoding=UTF-8
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME=localhost
      - KC_HTTP_ENABLED=true
      - KC_HTTP_PORT=8080
      - KC_LOG=syslog,console
      - KC_LOG_LEVEL=org.keycloak.events:debug,info
      - KC_LOG_SYSLOG_LEVEL=debug
      - KC_LOG_SYSLOG_ENDPOINT=host.docker.internal:5044
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_LOG_SYSLOG_TYPE=rfc3164
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
      - logstash
    networks:
      - elk


volumes:
  esdata:
  mariadb_data:


networks:
  elk:
    driver: bridge